# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 749aa7fa701cc72b7f5be5fdd8d6f2f8ab3223f3d4d06113ea1ab2ff97181177b8a176121951d938d8a7912bcbe067e55c5779ba045ee44d4cee88f11b1e762c

test:
  secret_key_base: 2a5243e1cfb4be4f72413bd2b301fc19602dcd6a89a7df7b023307de48033a16fbdbdce4a652a9f5ab381b650acd72098ce998fd8a1916b339208a3243f07f7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
